checks:
    php:
        code_rating: true
        duplication: true        
filter:
  paths: [src/*]
tools:
  php_code_sniffer:
    enabled: true
    config:
      standard: ./phpcs.xml
  php_sim: true
  php_changetracking: true
  php_cs_fixer: true
  php_mess_detector:
    enabled: true
    config:
      ruleset: ./phpmd.xml
  php_pdepend: true
  php_analyzer: true
  sensiolabs_security_checker: true
  php_code_coverage: true

