---
- name: Setup supervisord
  template: src=../templates/supervisord.conf.j2 dest=/etc/supervisor/supervisord.conf mode=744
  sudo: yes
  tags:
    - runner

- name: RestartSupervisor
  service: name=supervisor state=restarted
  sudo: yes
  tags:
    - runner